In [1]:
%pip install -q lyricsgenius python-dotenv pandas

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
from pathlib import Path

import pandas as pd
import lyricsgenius
from dotenv import load_dotenv

PROJECT_ROOT = Path.cwd().parent  # go up from notebooks to project root

load_dotenv(PROJECT_ROOT / '.env')

GENIUS_ACCESS_TOKEN = os.getenv('GENIUS_ACCESS_TOKEN')

if not GENIUS_ACCESS_TOKEN:
    raise ValueError('Missing GENIUS_ACCESS_TOKEN in .env')

## 1) Initialise Genius client

In [3]:
genius = lyricsgenius.Genius(
    GENIUS_ACCESS_TOKEN,
    timeout=15,
    retries=3,
    remove_section_headers=True,
    skip_non_songs=True
)
genius.verbose = False
print('Genius client ready.')

Genius client ready.

---
## Build per-region top songs from Spotify Charts

Reads the downloaded Spotify Charts CSVs and keeps only each region's top-ranked song.
No language detection is applied at this stage.

1. Merge all songs into single df with just `artist`, `title`, `spotify_uri`
2. Fetch lyrics into `lyrics`

Output columns: `rank`, `artist`, `title`, `region`, `spotify_uri`

In [ ]:
# Manually map filenames to regions for each run.

FILE_REGION_MAP = {
    'regional-ar-weekly-2026-03-05.csv': 'Argentina',
    'regional-es-weekly-2026-03-05.csv': 'Spain',
    'regional-jp-weekly-2026-03-05.csv': 'Japan',
    'regional-sg-weekly-2026-03-05.csv': 'Singapore',
}

Top-song extraction helpers loaded.

In [ ]:
from pathlib import Path
import pandas as pd
import re

PROJECT_ROOT = Path.cwd().parent  # go up from notebooks to project root
RAW_DIR = PROJECT_ROOT / 'data' / 'raw'

OUTPUT_PATH = PROJECT_ROOT / 'data' / 'processed' / '00_titles.csv'
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)



def extract_date_from_filename(filename: str) -> str:
    """Extract date in YYYY-MM-DD format from filename like 'regional-XX-weekly-YYYY-MM-DD.csv'"""
    match = re.search(r'(\d{4}-\d{2}-\d{2})', filename)
    return match.group(1) if match else None

dfs = []
for filename, region in FILE_REGION_MAP.items():
    chart_date = extract_date_from_filename(filename)
    df = pd.read_csv(RAW_DIR / filename)
    df = df.rename(columns={'artist_names': 'artist', 'track_name': 'title'})
    df['rank'] = pd.to_numeric(df['rank'], errors='coerce')
    df = df.dropna(subset=['rank'])

    df = df.assign(
        region=region,
        chart_date=chart_date,
        spotify_uri=df['uri'].str.replace('spotify:track:', '', regex=False)
    )[["rank", "artist", "title", "region", "chart_date", "spotify_uri"]]

    dfs.append(df)

titles_df = (
    pd.concat(dfs)
    .sort_values(['region', 'rank'])
    .reset_index(drop=True)
)

titles_df.to_csv(OUTPUT_PATH, index=False)

print(f'Saved to: {OUTPUT_PATH}')
print(f'Columns: {list(titles_df.columns)}')

Saved to: d:\Users\Documents\GitHub\lyrics_analysis\data\processed\00_titles.csv
Columns: ['rank', 'artist', 'title', 'region', 'chart_date', 'spotify_uri']

In [6]:
titles_df

,rank,artist,title,region,chart_date,spotify_uri
0,1,"Ryan Castro, Kapo, Gangsta",LA VILLA,Argentina,2026-03-05,2ZyrAym0sRLwt4PhGotHuI
1,2,Bad Bunny,BAILE INoLVIDABLE,Argentina,2026-03-05,2lTm559tuIvatlT1u0JYG2
2,3,"El Bogueto, Yung Beef",Cuando No Era Cantante,Argentina,2026-03-05,6N2iccqxRInhTLHc2Fu3W0
3,4,La T y La M,Soy Favela,Argentina,2026-03-05,3TfRpsYPQSXqqramSoWlNg
4,5,Max Carra,UWAIE - versión cumbia,Argentina,2026-03-05,6UO9DhCUq4ZbQz7PXwelFV
...,...,...,...,...,...,...
795,196,"Yapi, SOUNDPLUG",POR TI,Spain,2026-03-05,3Ip1sc72P5uz8BUB9kb4QQ
796,197,La Oreja de Van Gogh,Rosas,Spain,2026-03-05,4waqcUQWdj0yH26STWl2Rq
797,198,C. Tangana,Mala Mujer,Spain,2026-03-05,067QpM2xLhK24hTiovC3Zo
798,199,Sabrina Carpenter,Manchild,Spain,2026-03-05,2BwO5K8Q7EPAJSGze3AAh9
799,200,"John Pollõn, TylerB",Vehículo longo,Spain,2026-03-05,0GHaZd4ggGCx2RlMsDr9Vj

---
## Genius lyrics fetch from unique tracks in 00_titles.csv

Loads titles from data/processed/00_titles.csv, keeps unique tracks by:
`artist`, `title`, `spotify_uri`, then fetches lyrics and writes:
`data/processed/lyrics.csv`

Output columns in lyrics.csv:
`artist`, `title`, `spotify_uri`, `lyrics`

- Uses cache file for resumability
- Skips already fetched spotify_uri values
- Writes in chunks to avoid losing progress on interruption

In [ ]:
import time
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent  # go up from notebooks to project root
TITLES_PATH = PROJECT_ROOT / 'data' / 'processed' / '00_titles.csv'
CACHE_PATH = PROJECT_ROOT / 'data' / 'processed' / '01_01_01_01_lyrics_cache.csv'  # one row per unique track
LYRICS_OUT = PROJECT_ROOT / 'data' / 'processed' / 'lyrics.csv'        # unique tracks + lyrics + length

CHUNK_SIZE = 10     # flush cache every N fetched tracks
SLEEP_BETWEEN = 0.4 # seconds between Genius API calls

CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)

# Keep cache schema stable for resumability across old/new runs.
cache_cols = ['artist', 'title', 'spotify_uri', 'lyrics']
lyrics_cols = ['artist', 'title', 'spotify_uri', 'lyrics', 'length']

titles_df = pd.read_csv(TITLES_PATH)
unique_tracks = (
    titles_df[['artist', 'title', 'spotify_uri']]
    .dropna(subset=['spotify_uri'])
    .drop_duplicates(subset=['artist', 'title', 'spotify_uri'])
    .reset_index(drop=True)
)

print(f'Loaded titles: {len(titles_df)} rows')
print(f'Unique tracks for lyrics fetch: {len(unique_tracks)} rows')

Loaded titles: 800 rows
Unique tracks for lyrics fetch: 694 rows

In [ ]:
def fetch_lyrics_genius(client, title: str, artist: str) -> str:
    """Return lyrics string or empty string on failure."""
    try:
        hit = client.search_song(title=title, artist=artist)
        if hit and hit.lyrics:
            return hit.lyrics.strip()
    except Exception as e:
        print(f'  [warn] {title!r} by {artist!r}: {e}')
    return ''

def append_cache_chunk(rows_chunk: list[dict], out_path: Path) -> None:
    """Append cache rows (artist, title, spotify_uri, lyrics) to 01_01_01_01_lyrics_cache.csv."""
    if not rows_chunk:
        return
    chunk_df = pd.DataFrame(rows_chunk)[cache_cols]
    write_header = not out_path.exists()
    chunk_df.to_csv(out_path, mode='a', header=write_header, index=False)

# Resume: load existing cache
if CACHE_PATH.exists():
    cache_df = pd.read_csv(CACHE_PATH)
    fetched_uris = set(cache_df['spotify_uri'].astype(str))
    print(f'Cache: {len(fetched_uris)} tracks already fetched')
else:
    fetched_uris = set()
    print('No cache found, starting fresh')

# Pending tracks not yet in cache
pending = unique_tracks[~unique_tracks['spotify_uri'].astype(str).isin(fetched_uris)].reset_index(drop=True)
total = len(pending)
print(f'Tracks to fetch now: {total} (skipped {len(fetched_uris)} cached)')

# Fetch loop
if total == 0:
    print('All tracks already cached, skipping fetch.')
else:
    rows_buffer = []
    for i, row in enumerate(pending.itertuples(), 1):
        lyrics = fetch_lyrics_genius(genius, row.title, row.artist)
        rows_buffer.append({
            'artist': row.artist,
            'title': row.title,
            'spotify_uri': row.spotify_uri,
            'lyrics': lyrics,
        })

        status = 'ok' if lyrics else 'missing'
        print(f'[{i}/{total}] {status} | {row.title[:60]}')

        if len(rows_buffer) >= CHUNK_SIZE:
            append_cache_chunk(rows_buffer, CACHE_PATH)
            print(f'  -> flushed {len(rows_buffer)} rows to cache')
            rows_buffer = []

        time.sleep(SLEEP_BETWEEN)

    if rows_buffer:
        append_cache_chunk(rows_buffer, CACHE_PATH)
        print(f'  -> flushed final {len(rows_buffer)} rows to cache')

# Finalize lyrics.csv with required schema (+ length)
cache_df = pd.read_csv(CACHE_PATH)
lyrics_df = (
    cache_df[['artist', 'title', 'spotify_uri', 'lyrics']]
    .drop_duplicates(subset=['artist', 'title', 'spotify_uri'])
    .assign(length=lambda d: d['lyrics'].fillna('').astype(str).str.len())
    .loc[:, lyrics_cols]
    .reset_index(drop=True)
)
lyrics_df.to_csv(LYRICS_OUT, index=False)
print(f'Wrote {len(lyrics_df)} rows to {LYRICS_OUT}')
print(f'Columns: {list(lyrics_df.columns)}')

No cache found, starting fresh
Tracks to fetch now: 694 (skipped 0 cached)
[1/694] ok | LA VILLA
[2/694] ok | BAILE INoLVIDABLE
[3/694] ok | Cuando No Era Cantante
[4/694] ok | Soy Favela
[5/694] missing | UWAIE - versión cumbia
[6/694] ok | Puñaladas
[7/694] ok | DtMF
[8/694] ok | Tu jardín con enanitos
[9/694] ok | VOY A LLeVARTE PA PR
[10/694] ok | Cuando No Era Cantante - Remix
  -> flushed 10 rows to cache
[11/694] ok | FOREVER TU GANTEL
[12/694] ok | TU VAS SIN (fav)
[13/694] ok | EoO
[14/694] ok | VeLDÁ
[15/694] ok | La Perla
[16/694] ok | NUEVAYoL
[17/694] ok | no tiene sentido
[18/694] ok | Amor de Vago
[19/694] ok | Pensamientos
[20/694] ok | La Plena - W Sound 05
  -> flushed 10 rows to cache
[21/694] ok | Niño
[22/694] ok | JETSKI - Remix
[23/694] ok | No Se Va
[24/694] ok | mi refe
[25/694] ok | YO y TÚ
[26/694] ok | SOLEAO
[27/694] ok | capaz (merengueton)
[28/694] ok | KLOuFRENS
[29/694] ok | Qué Pasaría...
[30/694] ok | LA CANCIÓN
  -> flushed 10 rows to cache
[31/694] ok | Como Eran Las Cosas
[32/694] ok | POR SI MAÑANA NO ESTOY
[33/694] ok | Daddy Yankee: Bzrp Music Sessions, Vol. 0/66
[34/694] ok | Tití Me Preguntó
[35/694] ok | Diles
[36/694] ok | QLOO*
[37/694] ok | Por Mil Noches
[38/694] ok | Con Otra
[39/694] ok | TENGO UN FEELING
[40/694] ok | J Balvin: Bzrp Music Sessions, Vol. 62/66
  -> flushed 10 rows to cache
[41/694] ok | YOGURCITO REMIX (feat. Kris R., ROA)
[42/694] ok | A las Nueve
[43/694] ok | End of Beginning
[44/694] ok | WELTiTA
[45/694] ok | Es un Secreto
[46/694] ok | Tan Lejos
[47/694] ok | Gil
[48/694] ok | HASTA QUE ME ENAMORO
[49/694] ok | Adiós
[50/694] ok | Fronteo
  -> flushed 10 rows to cache
[51/694] ok | NO ME QUIERO CASAR
[52/694] missing | Loco Enamorado I Varieté #4
[53/694] ok | Nunca quise
[54/694] ok | Creo
[55/694] ok | Me Rehúso
[56/694] ok | Piel
[57/694] ok | HACE CALOR
[58/694] ok | Un Ángel para Tu Soledad
[59/694] ok | TU MISTERIOSO ALGUIEN (CUARTETO) (feat. Miranda!)
[60/694] ok | WO OH OH
  -> flushed 10 rows to cache
[61/694] ok | Cuidado Que Te Supero
[62/694] ok | El Teléfono
[63/694] ok | LADRON
[64/694] ok | The Fate of Ophelia
[65/694] ok | Amanece
[66/694] ok | Pasos Al Costado
[67/694] ok | Sola (Remix)
[68/694] ok | Cuentame
[69/694] ok | Yo te conozco :):
[70/694] ok | Irresponsables
  -> flushed 10 rows to cache
[71/694] ok | 444
[72/694] ok | TODO KE VER
[73/694] ok | La Noche Sin Tí
[74/694] ok | Bicho de Ciudad
[75/694] ok | KOKO
[76/694] ok | Borro Cassette
[77/694] ok | Talento
[78/694] missing | Bastardo (feat. Ñengo Flow & Jere Klein)
[79/694] ok | Campanas en la Noche
[80/694] ok | SI ESTÁS CON ALGUIEN
  -> flushed 10 rows to cache
[81/694] ok | Hasta Que Dios Diga
[82/694] ok | Me Gusta
[83/694] ok | MONACO
[84/694] ok | amor de veraNO
[85/694] ok | Nunca Lo Olvides
[86/694] ok | Yo sé
[87/694] ok | Rara Vez
[88/694] ok | Túnel de la Vida
[89/694] ok | No Se Ve / Chingon
[90/694] ok | Cicatrices
  -> flushed 10 rows to cache
[91/694] ok | Resentia
[92/694] ok | Don’t Say You Love Me
[93/694] ok | La player (Bandolera)
[94/694] ok | Obsesionario en La Mayor
[95/694] ok | Dardos
[96/694] ok | Tú No Lo Amas
[97/694] ok | Un Osito de Peluche de Taiwán
[98/694] ok | Un Poco de Amor Francés
[99/694] missing | Quédate / Soy Favela / Lo que hay x aqui - En Vivo
[100/694] ok | El Doctorado
  -> flushed 10 rows to cache
[101/694] ok | Tu Misterioso Alguien
[102/694] missing | Si No Es Muy Tarde - Versión Cumbia
[103/694] ok | Si Antes Te Hubiera Conocido
[104/694] ok | COQUETA
[105/694] ok | Moscow Mule
[106/694] ok | La Morocha
[107/694] ok | Loco (Tu Forma De Ser)
[108/694] ok | ⁠LUCES DE COLORES
[109/694] ok | Every Breath You Take
[110/694] ok | Cuatro Babys (feat. Trap Capos, Noriel, Bryant Myers & Juhn)
  -> flushed 10 rows to cache
[111/694] ok | Cae el Sol
[112/694] ok | No Podrás - En Vivo
[113/694] ok | Puesto
[114/694] missing | Trátame Suavemente - Remasterizado 2007
[115/694] ok | Estaba Aqui Pensando
[116/694] ok | Encantadora
[117/694] ok | Otra Noche en Miami
[118/694] ok | Ojitos Lindos
[119/694] ok | TIKI TIKI
[120/694] ok | Ese Maldito Momento
  -> flushed 10 rows to cache
[121/694] ok | FAVORITA
[122/694] ok | UWAIE
[123/694] ok | Ella Dijo
[124/694] missing | Un Montón de Estrellas - En Vivo Gran Rex
[125/694] ok | El Loco
[126/694] ok | Flaca
[127/694] ok | Personalmente
[128/694] ok | Khé?
[129/694] ok | Será
[130/694] ok | Tu Falta De Querer
  -> flushed 10 rows to cache
[131/694] ok | Esa Estrella Era Mi Lujo
[132/694] ok | 444 - Remix
[133/694] ok | Imitadora
[134/694] ok | M.A.I
[135/694] ok | VAMOaCOCHI
[136/694] missing | Pobre Corazón - En Vivo
[137/694] ok | LUNA
[138/694] ok | ¿Qué Nos Pasó?
[139/694] ok | No Te Hagas
[140/694] ok | El Efecto
  -> flushed 10 rows to cache
[141/694] ok | Loca
[142/694] missing | Es Mi Culpa - Versión Cumbia
[143/694] ok | RAMEN PARA DOS
[144/694] ok | Fanatica Sensual
[145/694] ok | Tiroteo - Remix
[146/694] missing | Suena en la Previa, Vol. 2
[147/694] ok | De las 2 (feat. Bad Bunny & Arcángel)
[148/694] ok | PUTERÍ4
[149/694] ok | blackout 🧊
[150/694] ok | Q U E V A S H A C E R H O Y ?
  -> flushed 10 rows to cache
[151/694] missing | Conmigo Te Gustó
[152/694] ok | CAFé CON RON
[153/694] ok | Kyoto
[154/694] ok | Manchild
[155/694] missing | No Puedo Fingirlo
[156/694] ok | MOJABI GHOST
[157/694] ok | La Bestia Pop
[158/694] ok | NO LES DA
[159/694] ok | Hecha Pa' Mi
[160/694] ok | Un Finde | CROSSOVER #2
  -> flushed 10 rows to cache
[161/694] ok | Esclava - Remix
[162/694] ok | MOTINHA 2.0 (Mete Marcha) - Remix
[163/694] ok | Ya No Vuelvas (Versión Cuarteto)
[164/694] ok | Enséñame a Bailar
[165/694] ok | Die With A Smile
[166/694] ok | Fuego
[167/694] ok | QUE ME FALTE TODO
[168/694] ok | Tan Solo
[169/694] ok | FERXXO 151
[170/694] ok | Solo aquí
  -> flushed 10 rows to cache
[171/694] ok | Te invito a bailar
[172/694] ok | Otra Vez (feat. J Balvin)
[173/694] ok | TE CANTO BAJITO
[174/694] ok | El Perdedor
[175/694] ok | Manicomio
[176/694] ok | La Diabla
[177/694] ok | Si Estuviésemos Juntos
[178/694] ok | Perdonarte, ¿Para Qué?
[179/694] ok | Como Lo Hizo? - En Vivo
[180/694] missing | De Música Ligera - Remasterizado 2007
  -> flushed 10 rows to cache
[181/694] ok | Madura
[182/694] ok | Había una Vez...
[183/694] ok | Arde la Ciudad
[184/694] ok | QUE PRETENDES
[185/694] ok | Tu No Vive Asi (feat. Mambo Kingz & DJ Luian)
[186/694] ok | No Me Conoce - Remix
[187/694] missing | VIAJEMOS EN EL TIEMPO #1 | Quien Te Quiere Como Yo
[188/694] ok | Tarea Fina
[189/694] ok | En Privado
[190/694] ok | WHERE IS MY HUSBAND!
  -> flushed 10 rows to cache
[191/694] ok | Si Tu Novio Te Deja Sola
[192/694] ok | Verte De Cerca
[193/694] ok | Me Gustas Mucho
[194/694] ok | FAR AWAY
[195/694] ok | Ganas de Verte
[196/694] ok | Como Se Siente
[197/694] ok | MI AMOR
[198/694] ok | TURiSTA
[199/694] ok | quédate
[200/694] ok | Stateside + Zara Larsson
  -> flushed 10 rows to cache
[201/694] ok | IRIS OUT
[202/694] ok | lulu.
[203/694] ok | Bakuretsu Aishiteru
[204/694] ok | Blue Jeans
[205/694] ok | Sukisugite METSU!
[206/694] ok | ROSE
[207/694] ok | Five
[208/694] ok | ライラック
[209/694] ok | AIZO
[210/694] ok | 花束
  -> flushed 10 rows to cache
[211/694] ok | SAD SONG
[212/694] ok | ブルーアンバー
[213/694] ok | 夢中
[214/694] ok | Soranji
[215/694] ok | Cold Night
[216/694] ok | ハッピーエンド
[217/694] ok | 点描の唄
[218/694] ok | ダーリン
[219/694] ok | NON STOP
[220/694] ok | Drop
  -> flushed 10 rows to cache
[221/694] ok | Who
[222/694] ok | 高嶺の花子さん
[223/694] ok | 水平線
[224/694] ok | JANE DOE
[225/694] ok | 革命道中 - On The Way
[226/694] ok | ALL IN
[227/694] ok | 僕のこと
[228/694] ok | Bloom
[229/694] ok | ハレンチ
[230/694] ok | Kaiju no Hanauta
  -> flushed 10 rows to cache
[231/694] ok | 3XL
[232/694] ok | HAPPY BIRTHDAY
[233/694] ok | 青と夏
[234/694] ok | Theater
[235/694] ok | My Body
[236/694] ok | Kaiju
[237/694] ok | ケセラセラ
[238/694] ok | どうしてもどうしても
[239/694] ok | ヒロイン
[240/694] ok | カリスマックス - CHARISMAX
  -> flushed 10 rows to cache
[241/694] ok | クスシキ
[242/694] ok | Never Grow Up
[243/694] ok | セレナーデ
[244/694] ok | Golden
[245/694] ok | 恋
[246/694] ok | 恋風
[247/694] ok | Tiger
[248/694] ok | TEST ME
[249/694] ok | GOD_i
[250/694] ok | LAVALAVA
  -> flushed 10 rows to cache
[251/694] ok | Burning Flower
[252/694] ok | BAD LOVE
[253/694] ok | IRANAI
[254/694] ok | 君の恋人になったら
[255/694] ok | GOOD DAY
[256/694] ok | 瞬き
[257/694] ok | Sangatsu Kokonoka
[258/694] ok | 奏(かなで)
[259/694] ok | 幸せ
[260/694] ok | 愛をこめて花束を
  -> flushed 10 rows to cache
[261/694] ok | BANG BANG
[262/694] ok | オールドファッション
[263/694] ok | Marigold
[264/694] ok | 劇薬中毒
[265/694] ok | RUDE!
[266/694] ok | 愛を伝えたいだとか
[267/694] ok | とくべチュ、して
[268/694] ok | E Jan
[269/694] ok | MONTAGEM HIKARI
[270/694] ok | シルエット
  -> flushed 10 rows to cache
[271/694] ok | 君はロックを聴かない
[272/694] ok | インフェルノ
[273/694] missing | 恋人ごっこ
[274/694] ok | オドロウゼ！
[275/694] ok | Kirari
[276/694] missing | Setsugekka
[277/694] ok | 楓
[278/694] ok | チェリー
[279/694] ok | HYPNOTIZE
[280/694] ok | Pretender
  -> flushed 10 rows to cache
[281/694] ok | ダンスホール
[282/694] ok | 晴る
[283/694] ok | アイネクライネ
[284/694] ok | ドライフラワー
[285/694] ok | 怪盗
[286/694] ok | 春愁
[287/694] ok | なんでもないよ、
[288/694] ok | 幾億光年
[289/694] ok | 白日
[290/694] ok | HANABI
  -> flushed 10 rows to cache
[291/694] ok | Seikai
[292/694] ok | me me she
[293/694] ok | B-list
[294/694] ok | Zoo
[295/694] ok | SPECIALZ
[296/694] ok | GO
[297/694] ok | キセキ
[298/694] ok | Tokimeki
[299/694] ok | 新宝島
[300/694] ok | ロビンソン
  -> flushed 10 rows to cache
[301/694] ok | さよーならまたいつか！- Sayonara
[302/694] ok | ツキミソウ
[303/694] ok | クリスマスソング
[304/694] ok | Fukakoryoku
[305/694] ok | Tabiji
[306/694] ok | Lemon
[307/694] ok | プロポーズ
[308/694] ok | Naked Heart
[309/694] missing | Again
[310/694] ok | パズル
  -> flushed 10 rows to cache
[311/694] ok | Be Mine
[312/694] ok | 春泥棒
[313/694] ok | ただ君に晴れ
[314/694] ok | Shape of You
[315/694] ok | Garden
[316/694] ok | First Love
[317/694] ok | 晩餐歌 - Bansanka
[318/694] ok | Subtitle
[319/694] ok | Magic
[320/694] ok | アゲハ蝶
  -> flushed 10 rows to cache
[321/694] ok | Rashisa
[322/694] ok | I Love...
[323/694] ok | Us, again
[324/694] ok | 115 million kilometer film
[325/694] ok | Harunohi
[326/694] ok | 茜
[327/694] ok | 愛とか恋とか
[328/694] ok | JUMP
[329/694] ok | ベテルギウス
[330/694] ok | Make Me Wonder
  -> flushed 10 rows to cache
[331/694] ok | Tiger – HANA with HONEYs Ver.
[332/694] ok | 踊り子
[333/694] ok | さよならエレジー
[334/694] ok | KICK BACK
[335/694] ok | BAIBAI FIGHT!
[336/694] ok | 感電
[337/694] ok | ブルーベリー・ナイツ
[338/694] ok | 404 (New Era)
[339/694] ok | Stand by me, Stand by you.
[340/694] missing | ぬくもり
  -> flushed 10 rows to cache
[341/694] ok | 花占い
[342/694] ok | BLACKHOLE
[343/694] ok | Michi Teyu Ku (Overflowing)
[344/694] ok | ロマンチシズム
[345/694] ok | Itsuka
[346/694] ok | 愛唄
[347/694] ok | 花火
[348/694] ok | SAD SONG - From THE FIRST TAKE
[349/694] missing | World is Mine - Kaguya&Yachiyo Runami ver. - CPK! Remix
[350/694] ok | Hana
  -> flushed 10 rows to cache
[351/694] ok | W / X / Y
[352/694] ok | napori
[353/694] ok | 遥か
[354/694] ok | Cinderella Boy
[355/694] ok | アイラブユー
[356/694] ok | 日曜日
[357/694] missing | ミスター・ブルースカイ
[358/694] ok | Let the Night
[359/694] ok | 花束を君に
[360/694] missing | 織姫とBABY
  -> flushed 10 rows to cache
[361/694] ok | ファンファーレ
[362/694] ok | Love So Sweet
[363/694] ok | 小さな恋のうた
[364/694] ok | 1991
[365/694] ok | 新しい恋人達に
[366/694] ok | STARS
[367/694] ok | 未確認領域
[368/694] ok | 空も飛べるはず
[369/694] ok | Seven (feat. Latto) (Explicit Ver.)
[370/694] ok | 春雷
  -> flushed 10 rows to cache
[371/694] ok | 呼び声
[372/694] ok | Tokyo Flash
[373/694] ok | BOW AND ARROW
[374/694] ok | Angel
[375/694] missing | ray - Cosmic Princess Kaguya! Version
[376/694] missing | また逢う日まで
[377/694] ok | ワタリドリ
[378/694] ok | 1000 days of moments
[379/694] ok | Tontsukatantan
[380/694] ok | 一秒
  -> flushed 10 rows to cache
[381/694] ok | イケナイ太陽
[382/694] ok | breakfast
[383/694] ok | APT.
[384/694] missing | アイノカタチ
[385/694] ok | Wherever you are
[386/694] ok | だから僕は音楽を辞めた
[387/694] ok | 街灯
[388/694] ok | 僕は君の事が好きだけど君は僕を別に好きじゃないみたい
[389/694] ok | ラブソングに襲われる
[390/694] ok | 美しい鰭
  -> flushed 10 rows to cache
[391/694] ok | I wonder
[392/694] ok | 世界が終わりました
[393/694] ok | 逆夢
[394/694] ok | Story
[395/694] ok | 366日
[396/694] ok | PUZZLE
[397/694] ok | 一途
[398/694] ok | カメレオン
[399/694] ok | ビリミリオン
[400/694] ok | Risk It All
  -> flushed 10 rows to cache
[401/694] ok | So Easy (To Fall In Love)
[402/694] ok | Champion
[403/694] ok | back to friends
[404/694] ok | Running Wild
[405/694] ok | I Just Might
[406/694] ok | Jumping Machine (跳楼机)
[407/694] ok | Man I Need
[408/694] ok | Opalite
[409/694] ok | Who Knows
[410/694] ok | 看着我的眼睛说
  -> flushed 10 rows to cache
[411/694] ok | Die On This Hill
[412/694] ok | Raindance (feat. Tems)
[413/694] ok | like JENNIE
[414/694] ok | Fxxxboy
[415/694] ok | Me and my
[416/694] ok | bittersweet
[417/694] ok | Lush Life
[418/694] ok | BIRDS OF A FEATHER
[419/694] ok | Love Me Not
[420/694] ok | Dracula - JENNIE Remix
  -> flushed 10 rows to cache
[421/694] ok | Homewrecker
[422/694] ok | The Man Who Can't Be Moved
[423/694] ok | Ordinary
[424/694] ok | Gabriela
[425/694] ok | Good Goodbye
[426/694] ok | I Thought I Saw Your Face Today
[427/694] ok | Babydoll
[428/694] missing | 像晴天像雨天（电视剧《难哄》心动曲）
[429/694] ok | About You
[430/694] missing | 善后
  -> flushed 10 rows to cache
[431/694] ok | Cha Cha Cha
[432/694] ok | 嘉賓
[433/694] ok | Sailor Song
[434/694] ok | WILDFLOWER
[435/694] ok | CHANEL
[436/694] ok | That’s So True
[437/694] ok | NOT CUTE ANYMORE
[438/694] ok | Iris
[439/694] ok | 擱淺
[440/694] ok | God Was Showing Off
  -> flushed 10 rows to cache
[441/694] ok | NO BATIDÃO
[442/694] ok | Yellow
[443/694] ok | Dance With Me
[444/694] ok | That's What I Like
[445/694] ok | Folded
[446/694] ok | toxic till the end
[447/694] ok | Drag Path
[448/694] ok | Fame is a Gun
[449/694] ok | E85
[450/694] ok | Night Changes
  -> flushed 10 rows to cache
[451/694] ok | Winter Ahead (with PARK HYO SHIN)
[452/694] missing | One Of The Girls (with JENNIE, Lily Rose Depp)
[453/694] ok | DAISIES
[454/694] ok | Why You Wanna Fight?
[455/694] ok | luther (with sza)
[456/694] missing | 福气马上来
[457/694] ok | we can't be friends (wait for your love)
[458/694] missing | 这是你期盼的长大吗
[459/694] missing | Just Keep Watching (From F1® The Movie)
[460/694] ok | Just the Way You Are
  -> flushed 10 rows to cache
[461/694] ok | 在加納共和國離婚
[462/694] ok | 爱怎么了
[463/694] ok | No One Noticed
[464/694] ok | 晴天
[465/694] ok | Sweet Boy
[466/694] ok | 3D (feat. Jack Harlow)
[467/694] missing | 離開我的依賴
[468/694] ok | Cruel Summer
[469/694] ok | Espresso
[470/694] ok | number one girl
  -> flushed 10 rows to cache
[471/694] ok | blue
[472/694] ok | We Don't Talk Anymore (feat. Selena Gomez)
[473/694] ok | Eenie Meenie
[474/694] ok | Style
[475/694] ok | From The Start
[476/694] missing | 人的這一生
[477/694] ok | Viva La Vida
[478/694] ok | No Broke Boys
[479/694] ok | Closer
[480/694] ok | Something Just Like This
  -> flushed 10 rows to cache
[481/694] ok | Photograph
[482/694] ok | Payphone
[483/694] ok | It Will Rain
[484/694] ok | Ghost
[485/694] ok | Love Me Harder
[486/694] ok | On My Soul
[487/694] ok | All The Stars (with SZA) - From "Black Panther: The Album"
[488/694] ok | Sparks
[489/694] missing | 你，好不好？ - TVBS連續劇【遺憾拼圖】片尾曲
[490/694] ok | 12 to 12
  -> flushed 10 rows to cache
[491/694] ok | Always
[492/694] ok | Sweater Weather
[493/694] ok | Somewhere Only We Know
[494/694] ok | Beautiful Things
[495/694] ok | SLOW DANCING IN THE DARK
[496/694] ok | Standing Next to You
[497/694] ok | Multo
[498/694] ok | Moonwalkin'
[499/694] ok | Sienna
[500/694] ok | Locked out of Heaven
  -> flushed 10 rows to cache
[501/694] ok | 座位
[502/694] ok | Nothin' on You (feat. Bruno Mars)
[503/694] ok | Snooze
[504/694] ok | Perfect
[505/694] ok | Counting Stars
[506/694] ok | Apocalypse
[507/694] ok | Talking to the Moon
[508/694] ok | EYES CLOSED (with ZAYN)
[509/694] missing | 最后一页 - Live
[510/694] ok | Earrings
  -> flushed 10 rows to cache
[511/694] ok | Beauty And A Beat
[512/694] ok | I Wanna Be Yours
[513/694] ok | As It Was
[514/694] ok | When I Was Your Man
[515/694] ok | Soda Pop
[516/694] ok | Sports car
[517/694] ok | 珊瑚海
[518/694] ok | Starboy
[519/694] ok | Soft Spot
[520/694] ok | A Couple Minutes
  -> flushed 10 rows to cache
[521/694] ok | SPAGHETTI
[522/694] ok | 演员
[523/694] ok | Attention
[524/694] ok | Good Luck, Babe!
[525/694] ok | 過了幾天(合唱版)
[526/694] ok | 特別的人
[527/694] missing | 感谢你曾来过
[528/694] missing | 嚣张
[529/694] ok | Let Down
[530/694] ok | Timeless (feat Playboi Carti)
  -> flushed 10 rows to cache
[531/694] ok | Touch
[532/694] ok | Kiss It Better
[533/694] ok | FEVER DREAM
[534/694] ok | 告白氣球
[535/694] ok | Midnight Sun
[536/694] ok | 从前说
[537/694] ok | Nothing Left
[538/694] ok | 怎麼了
[539/694] ok | undressed
[540/694] ok | The One That Got Away
  -> flushed 10 rows to cache
[541/694] ok | STAY (with Justin Bieber)
[542/694] ok | One Last Time
[543/694] missing | 如果可以 - 電影"月老"主題曲
[544/694] ok | double take
[545/694] ok | Sorry
[546/694] ok | Let Me Love You
[547/694] ok | Magnetic
[548/694] ok | Life Goes On
[549/694] ok | Blank Space
[550/694] ok | The Scientist
  -> flushed 10 rows to cache
[551/694] ok | 青花瓷
[552/694] ok | Cry
[553/694] ok | Dive
[554/694] ok | Promise
[555/694] ok | Something Serious
[556/694] missing | 我走后 (深情版)
[557/694] ok | Versace on the Floor
[558/694] ok | I Love You, I'm Sorry
[559/694] ok | Best Part (feat. H.E.R.)
[560/694] ok | Creep
  -> flushed 10 rows to cache
[561/694] ok | GO!
[562/694] ok | party 4 u
[563/694] ok | Nobody Gets Me
[564/694] ok | Glimpse of Us
[565/694] ok | Into You
[566/694] ok | 楓
[567/694] ok | 遇見
[568/694] ok | Here With Me
[569/694] ok | Cinnamon Girl
[570/694] ok | kota ini tak sama tanpamu
  -> flushed 10 rows to cache
[571/694] missing | 字字句句
[572/694] ok | greedy
[573/694] ok | Never Let Go
[574/694] ok | Adrenaline
[575/694] ok | I Like Me Better
[576/694] ok | Love Yourself
[577/694] ok | Young And Beautiful
[578/694] ok | NI BORRACHO
[579/694] ok | $UELTA GATITA $UELTA
[580/694] ok | SUPERESTRELLA
  -> flushed 10 rows to cache
[581/694] ok | BIENVENIDA
[582/694] ok | LOQUITA
[583/694] ok | TUCHAT
[584/694] ok | MVLAN
[585/694] ok | Me Mareo
[586/694] ok | Choque
[587/694] ok | LOVE
[588/694] ok | Bad Voy
[589/694] ok | COMERNOS
[590/694] ok | WHAT U NEED? (SexPlaylist 2)
  -> flushed 10 rows to cache
[591/694] ok | DROGA
[592/694] ok | Que culpa tiene el lunes de no ser un sabado
[593/694] ok | El Fin del Mundo
[594/694] ok | Still Luvin
[595/694] ok | CUPIDOxX
[596/694] missing | NYX00 (with JC Reyes)
[597/694] ok | PINKY PROMISE 2
[598/694] ok | EL MUNDO SE VA A ACABAR
[599/694] ok | AURORA
[600/694] ok | CHUOS
  -> flushed 10 rows to cache
[601/694] ok | SETEADORA REMIX (with JC Reyes)
[602/694] ok | malibU
[603/694] ok | FLAITEERA
[604/694] ok | MUCHACHA
[605/694] ok | 6 DE FEBRERO
[606/694] ok | LA SACAPUNTAS
[607/694] ok | La vereda de la puerta de atrás
[608/694] ok | ROSITA
[609/694] ok | Scat Pack
[610/694] ok | La Salvación
  -> flushed 10 rows to cache
[611/694] ok | Inglés En Miami
[612/694] ok | Lokita Por Mí
[613/694] ok | SIRENA
[614/694] ok | La Bachata
[615/694] ok | L a k e n o s h i
[616/694] ok | IA
[617/694] ok | Duro Ma
[618/694] ok | HALO
[619/694] ok | Me has invitado a bailar
[620/694] ok | El Bien
  -> flushed 10 rows to cache
[621/694] ok | DETRÁS DE TU ALMA
[622/694] ok | Fecha de Caducidad
[623/694] ok | Bailando por Ahi
[624/694] missing | DA LA LUZ
[625/694] ok | Por la boca vive el pez
[626/694] ok | MOONLIGHT
[627/694] ok | BARRIO FINO
[628/694] ok | TOCATE SOLA
[629/694] ok | Te Capie
[630/694] ok | Da Me
  -> flushed 10 rows to cache
[631/694] ok | Si te vas...
[632/694] ok | Bailando Bachata
[633/694] ok | UNA NOTi
[634/694] ok | SKY
[635/694] ok | El Merengue
[636/694] ok | Todos los Besos
[637/694] ok | YSL
[638/694] missing | Dichavate
[639/694] ok | GRAN VÍA
[640/694] ok | FLIPA

In [9]:
lyrics_df = pd.read_csv(LYRICS_OUT)

print(f'Saved rows: {len(lyrics_df)}')
print(f'Output path: {LYRICS_OUT}')
print(f'Columns: {list(lyrics_df.columns)}')

coverage = (
    lyrics_df
    .assign(has_lyrics=lyrics_df['lyrics'].fillna('').str.strip().ne(''))['has_lyrics']
    .value_counts()
)

print('\nLyrics availability:')
print(coverage.to_string())

lyrics_df.head(10)

Saved rows: 694
Output path: d:\Users\Documents\GitHub\lyrics_analysis\data\processed\lyrics.csv
Columns: ['artist', 'title', 'spotify_uri', 'lyrics']

Lyrics availability:
has_lyrics
True     652
False     42

,artist,title,spotify_uri,lyrics
0,"Ryan Castro, Kapo, Gangsta",LA VILLA,2ZyrAym0sRLwt4PhGotHuI,"Kapo, Ryan Castro, Gangsta\nQué chimba, SOG\nT..."
1,Bad Bunny,BAILE INoLVIDABLE,2lTm559tuIvatlT1u0JYG2,Pensaba que contigo iba a envejecer\nEn otra v...
2,"El Bogueto, Yung Beef",Cuando No Era Cantante,6N2iccqxRInhTLHc2Fu3W0,"Jajajajaja\nJaja, QueHicisteBella\n\nComo ante..."
3,La T y La M,Soy Favela,3TfRpsYPQSXqqramSoWlNg,¡Ay!\n\nHe caminado tantas calles pero no he e...
4,Max Carra,UWAIE - versión cumbia,6UO9DhCUq4ZbQz7PXwelFV,NaN
5,"Lauta, Amigo de Artistas, Tote",Puñaladas,4AL4EamHEBKPpdcFRkYdXN,"Si tu espejo hablara, te diría esto\n\nEsa car..."
6,Bad Bunny,DtMF,3sK8wGT43QFpWrvNQsrQya,"Eh, eh, eh, eh\n\nOtro sunset bonito que veo e..."
7,"Roze Oficial, Max Carra, Valen, RAMKY EN LOS C...",Tu jardín con enanitos,6X8DTIJEgHUjZynuds0E2f,"Con este tema, te voy a hacer viajar en el tie..."
8,Bad Bunny,VOY A LLeVARTE PA PR,59D4DOkspUbWyMmbAPQkxZ,"Acho, PR es otra cosa\nYo la conocí en Miami, ..."
9,"El Bogueto, Anuel AA, Fuerza Regida, Yung Beef",Cuando No Era Cantante - Remix,2pbSCYzxrG0wa6qcj8IyiE,Uh-uh-uh\nHow pretty that ass loo-oo-ooks\nIn ...

In [ ]:
# # RUN ONCE, THEN DELETE THIS CELL
# from pathlib import Path
# import pandas as pd

# PROJECT_ROOT = Path.cwd().parent
# output_path = PROJECT_ROOT / "data" / "processed" / "lyrics.csv"

# df = pd.read_csv(output_path)

# if "length" not in df.columns:
#     # Quick backfill: length of translated lyrics text in characters
#     df["length"] = df["lyrics"].fillna("").astype(str).str.len()
#     df.to_csv(output_path, index=False)
#     print(f"Added length column and overwrote: {output_path}")
# else:
#     print("length column already exists; no changes made.")

# print(f"Columns now: {list(df.columns)}")
# display(df[["spotify_uri", "lyrics", "length"]].head(10))

Added length column and overwrote: d:\Users\Documents\GitHub\lyrics_analysis\data\processed\lyrics.csv
Columns now: ['artist', 'title', 'spotify_uri', 'lyrics', 'length']

,spotify_uri,lyrics,length
0,2ZyrAym0sRLwt4PhGotHuI,"Kapo, Ryan Castro, Gangsta\nQué chimba, SOG\nT...",2484
1,2lTm559tuIvatlT1u0JYG2,Pensaba que contigo iba a envejecer\nEn otra v...,2083
2,6N2iccqxRInhTLHc2Fu3W0,"Jajajajaja\nJaja, QueHicisteBella\n\nComo ante...",2515
3,3TfRpsYPQSXqqramSoWlNg,¡Ay!\n\nHe caminado tantas calles pero no he e...,1429
4,6UO9DhCUq4ZbQz7PXwelFV,NaN,0
5,4AL4EamHEBKPpdcFRkYdXN,"Si tu espejo hablara, te diría esto\n\nEsa car...",1350
6,3sK8wGT43QFpWrvNQsrQya,"Eh, eh, eh, eh\n\nOtro sunset bonito que veo e...",2403
7,6X8DTIJEgHUjZynuds0E2f,"Con este tema, te voy a hacer viajar en el tie...",1576
8,59D4DOkspUbWyMmbAPQkxZ,"Acho, PR es otra cosa\nYo la conocí en Miami, ...",1923
9,2pbSCYzxrG0wa6qcj8IyiE,Uh-uh-uh\nHow pretty that ass loo-oo-ooks\nIn ...,5006