In [45]:
import pandas as pd

file1 = r"D:\Users\Documents\GitHub\lyrics_analysis\data\processed\co_global_tw_usa\lyrics_lang.csv"
file2 = r"D:\Users\Documents\GitHub\lyrics_analysis\data\processed\sg_es_ar_jp\02_lyrics_lang.csv"

df1 = pd.read_csv(file1)
df2 = pd.read_csv(file2)

print(f"Length of df1: {len(df1)}")
display(df1.head())
print(f"\n Length of df2: {len(df2)}")
display(df2.head())

Length of df1: 754

,rank,artist,title,region,spotify_uri,lyrics,language
0,1,"Mr Plata, El Americano 4KT",Las Muñequitas,Colombia,4nJJCRYru4QQakCiUA155f,"(Dímelo, ¿me vas a dar lo que yo pido?)\r\nDam...",es
1,2,"ARIA VEGA, Ryan Castro",CHÉVERE (premium_remix),Colombia,3CBEVPwR3kUXDoTx1lqFUQ,"ARIA VEGA, Ryan Castro\r\nLa costeñita premium...",es
2,3,"Ryan Castro, Kapo, Gangsta",LA VILLA,Colombia,2ZyrAym0sRLwt4PhGotHuI,"Kapo, Ryan Castro, Gangsta\r\nQué chimba, SOG\...",es
3,4,Kris R.,GANAS,Colombia,4KE9Ne3hgh18B3Th4xcylg,"Yeah, yeah\r\nYeah, yeah\r\n\r\nMi amor, culee...",es
4,5,"W Sound, Beéle, Ovy On The Drums",La Plena - W Sound 05,Colombia,6iOndD4OFo7GkaDypWQIou,O-O-Ovy On The Drums\r\nYou're the apple of my...,en

 Length of df2: 694

,artist,title,spotify_uri,lyrics,length,original_lang
0,"Ryan Castro, Kapo, Gangsta",LA VILLA,2ZyrAym0sRLwt4PhGotHuI,"Kapo, Ryan Castro, Gangsta\nQué chimba, SOG\nT...",2484,es
1,Bad Bunny,BAILE INoLVIDABLE,2lTm559tuIvatlT1u0JYG2,Pensaba que contigo iba a envejecer\nEn otra v...,2083,es
2,"El Bogueto, Yung Beef",Cuando No Era Cantante,6N2iccqxRInhTLHc2Fu3W0,"Jajajajaja\nJaja, QueHicisteBella\n\nComo ante...",2515,es
3,La T y La M,Soy Favela,3TfRpsYPQSXqqramSoWlNg,¡Ay!\n\nHe caminado tantas calles pero no he e...,1429,es
4,Max Carra,UWAIE - versión cumbia,6UO9DhCUq4ZbQz7PXwelFV,NaN,0,unknown

In [46]:
df1["length"] = df1['lyrics'].str.len().astype('Int64')
df1.rename(columns={"language": "original_lang"}, inplace=True)
df1.drop(columns=["rank","region"], inplace=True)

display(df1.head())

,artist,title,spotify_uri,lyrics,original_lang,length
0,"Mr Plata, El Americano 4KT",Las Muñequitas,4nJJCRYru4QQakCiUA155f,"(Dímelo, ¿me vas a dar lo que yo pido?)\r\nDam...",es,3033
1,"ARIA VEGA, Ryan Castro",CHÉVERE (premium_remix),3CBEVPwR3kUXDoTx1lqFUQ,"ARIA VEGA, Ryan Castro\r\nLa costeñita premium...",es,2978
2,"Ryan Castro, Kapo, Gangsta",LA VILLA,2ZyrAym0sRLwt4PhGotHuI,"Kapo, Ryan Castro, Gangsta\r\nQué chimba, SOG\...",es,2558
3,Kris R.,GANAS,4KE9Ne3hgh18B3Th4xcylg,"Yeah, yeah\r\nYeah, yeah\r\n\r\nMi amor, culee...",es,2159
4,"W Sound, Beéle, Ovy On The Drums",La Plena - W Sound 05,6iOndD4OFo7GkaDypWQIou,O-O-Ovy On The Drums\r\nYou're the apple of my...,en,1890

In [47]:
df_appended = pd.concat([df1, df2[df1.columns]], ignore_index=True)

print(f"\n Length of appended DataFrame: {len(df_appended)}")
display(df_appended.head())

 Length of appended DataFrame: 1448

,artist,title,spotify_uri,lyrics,original_lang,length
0,"Mr Plata, El Americano 4KT",Las Muñequitas,4nJJCRYru4QQakCiUA155f,"(Dímelo, ¿me vas a dar lo que yo pido?)\r\nDam...",es,3033
1,"ARIA VEGA, Ryan Castro",CHÉVERE (premium_remix),3CBEVPwR3kUXDoTx1lqFUQ,"ARIA VEGA, Ryan Castro\r\nLa costeñita premium...",es,2978
2,"Ryan Castro, Kapo, Gangsta",LA VILLA,2ZyrAym0sRLwt4PhGotHuI,"Kapo, Ryan Castro, Gangsta\r\nQué chimba, SOG\...",es,2558
3,Kris R.,GANAS,4KE9Ne3hgh18B3Th4xcylg,"Yeah, yeah\r\nYeah, yeah\r\n\r\nMi amor, culee...",es,2159
4,"W Sound, Beéle, Ovy On The Drums",La Plena - W Sound 05,6iOndD4OFo7GkaDypWQIou,O-O-Ovy On The Drums\r\nYou're the apple of my...,en,1890

In [48]:
new_file = r"D:\Users\Documents\GitHub\lyrics_analysis\data\processed\new_02_lyrics_lang.csv"

df_appended.to_csv(new_file, index=False)